# Generated by Django 5.1.2 on 2024-11-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_category_alter_expense_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
